# Generated by Django 2.1.5 on 2019-01-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20190130_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flagkliring',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='flagkliring',
            name='leader',
        ),
        migrations.AlterField(
            model_name='kliring',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.KlirPayment'),
        ),
        migrations.DeleteModel(
            name='FlagKliring',
        ),
    ]
