# Generated by Django 2.1.5 on 2019-01-28 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instanpay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InqueryResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('kode_produk', models.CharField(blank=True, max_length=200)),
                ('waktu', models.CharField(blank=True, max_length=200)),
                ('idpel1', models.CharField(blank=True, max_length=200)),
                ('idpel2', models.CharField(blank=True, max_length=200)),
                ('idpel3', models.CharField(blank=True, max_length=200)),
                ('nama_palanggan', models.CharField(blank=True, max_length=200)),
                ('periode', models.CharField(blank=True, max_length=200)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('admin', models.PositiveIntegerField(default=0)),
                ('ref1', models.CharField(blank=True, max_length=200)),
                ('ref2', models.CharField(blank=True, max_length=200)),
                ('ref3', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('ket', models.CharField(blank=True, max_length=200)),
                ('saldo_terpotong', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sisa_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('url_struk', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('kode_produk', models.CharField(blank=True, max_length=200)),
                ('waktu', models.CharField(blank=True, max_length=200)),
                ('idpel1', models.CharField(blank=True, max_length=200)),
                ('idpel2', models.CharField(blank=True, max_length=200)),
                ('idpel3', models.CharField(blank=True, max_length=200)),
                ('nama_palanggan', models.CharField(blank=True, max_length=200)),
                ('periode', models.CharField(blank=True, max_length=200)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('admin', models.PositiveIntegerField(default=0)),
                ('ref1', models.CharField(blank=True, max_length=200)),
                ('ref2', models.CharField(blank=True, max_length=200)),
                ('ref3', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('ket', models.CharField(blank=True, max_length=200)),
                ('saldo_terpotong', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sisa_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('url_struk', models.CharField(blank=True, max_length=200)),
                ('detail', models.TextField(blank=True, max_length=3000)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('trx_code', models.SlugField(editable=False, max_length=20, unique=True)),
                ('customer', models.CharField(max_length=50)),
                ('subtype', models.CharField(choices=[('INQ', 'Inquery'), ('PAY', 'Pay')], default='INQ', max_length=3)),
                ('product_code', models.CharField(blank=True, max_length=20)),
                ('server_group', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('PR', 'In Process'), ('CO', 'Complete'), ('FL', 'Failed')], default='OP', max_length=2)),
                ('inquery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppob.Transaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inq_product', to='instanpay.Product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inq_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='paymentresponse',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trx_pay', to='ppob.Transaction'),
        ),
        migrations.AddField(
            model_name='inqueryresponse',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trx_inq', to='ppob.Transaction'),
        ),
    ]
