# Generated by Django 2.1.5 on 2019-01-28 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, max_length=20, unique=True)),
                ('group_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('operator_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=4, unique=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instanpay.Operator')),
            ],
            options={
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('subtype', models.CharField(choices=[('I', 'Instan Product'), ('Q', 'Product Inquery')], default='I', max_length=1)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('extend_server', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instanpay.ExtraServer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instanpay.Group')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instanpay.Operator')),
            ],
            options={
                'ordering': ['group', 'operator', '-nominal'],
            },
        ),
        migrations.CreateModel(
            name='ServerResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('kode_produk', models.CharField(blank=True, max_length=200)),
                ('waktu', models.CharField(blank=True, max_length=200)),
                ('no_hp', models.CharField(blank=True, max_length=200)),
                ('sn', models.CharField(blank=True, max_length=200)),
                ('nominal', models.IntegerField(default=0)),
                ('ref1', models.CharField(blank=True, max_length=200)),
                ('ref2', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('ket', models.CharField(blank=True, max_length=200)),
                ('saldo_terpotong', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sisa_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('trx_code', models.SlugField(editable=False, max_length=20, unique=True)),
                ('customer', models.CharField(max_length=50)),
                ('product_code', models.CharField(blank=True, max_length=20)),
                ('server_group', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('PR', 'In Process'), ('CO', 'Complete'), ('FL', 'Failed')], default='OP', max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instanpay.Product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='serverresponse',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instanpay.Transaction'),
        ),
        migrations.AddField(
            model_name='operator',
            name='group',
            field=models.ManyToManyField(through='instanpay.Product', to='instanpay.Group'),
        ),
        migrations.AddField(
            model_name='extraserver',
            name='group_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instanpay.GroupServer'),
        ),
    ]
